env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  project: tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
root: true
env:
  node: true
  jest: true
ignorePatterns: ['.eslintrc.js']
rules:
  @typescript-eslint/interface-name-prefix': 0
  @typescript-eslint/explicit-function-return-type': 0
  @typescript-eslint/explicit-module-boundary-types': 0
  @typescript-eslint/no-explicit-any': 0
  new-cap: 0,
