env:
  browser: true
  es2017: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 8
  project: tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'
extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
root: true
ignorePatterns: ['.eslintrc.js']
rules:
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  new-cap: off
  require-jsdoc: off
overrides:
  - files: ['src/**/*.entity.ts']
    rules:
      '@typescript-eslint/no-unused-vars': off
